# Copyright (c) 2024 Antonio S. Cofiño
# Licensed under the Mozilla Public License, v. 2.0. See LICENSE file for details.
name: cf-zenodo

channels:
  - conda-forge

dependencies:
  # Core dependencies from conda
  - python=3.10  # Using Python 3.10 for compatibility with most libraries
  - pip
  - requests
  
  # Pip dependencies not available on conda-forge, so we install it via pip
  - pip:
    #- inveniordm-py  # Python client for the InvenioRDM REST API
    - -e ./utils/inveniordm-py  # Editable mode from local path